<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkpbiei\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkpbiei/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPkpbiei.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPkpbiei\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPkpbiei\appProdProjectContainer([
    'container.build_hash' => 'Pkpbiei',
    'container.build_id' => '8311ead5',
    'container.build_time' => 1697189011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkpbiei');
